In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
#Generate Student data
# Student:
#     RollNumber MPMC  EMTL CO AWS
    
#     20ECE101   82    89   54 69

Roll_numbers=["192U1A0"+str(i) for i in range(401,500)]
print(Roll_numbers)
print(len(Roll_numbers))
MPMC=np.random.randint(0,100,99)
print(MPMC)
print(len(MPMC))
EMTL=np.random.randint(0,100,99)
CO=np.random.randint(0,100,99)
AWP=np.random.randint(0,100,99)

['192U1A0401', '192U1A0402', '192U1A0403', '192U1A0404', '192U1A0405', '192U1A0406', '192U1A0407', '192U1A0408', '192U1A0409', '192U1A0410', '192U1A0411', '192U1A0412', '192U1A0413', '192U1A0414', '192U1A0415', '192U1A0416', '192U1A0417', '192U1A0418', '192U1A0419', '192U1A0420', '192U1A0421', '192U1A0422', '192U1A0423', '192U1A0424', '192U1A0425', '192U1A0426', '192U1A0427', '192U1A0428', '192U1A0429', '192U1A0430', '192U1A0431', '192U1A0432', '192U1A0433', '192U1A0434', '192U1A0435', '192U1A0436', '192U1A0437', '192U1A0438', '192U1A0439', '192U1A0440', '192U1A0441', '192U1A0442', '192U1A0443', '192U1A0444', '192U1A0445', '192U1A0446', '192U1A0447', '192U1A0448', '192U1A0449', '192U1A0450', '192U1A0451', '192U1A0452', '192U1A0453', '192U1A0454', '192U1A0455', '192U1A0456', '192U1A0457', '192U1A0458', '192U1A0459', '192U1A0460', '192U1A0461', '192U1A0462', '192U1A0463', '192U1A0464', '192U1A0465', '192U1A0466', '192U1A0467', '192U1A0468', '192U1A0469', '192U1A0470', '192U1A0471', '192U1A0472', '192U1A0473', '192U1A0474', '192U1A0475', '192U1A0476', '192U1A0477', '192U1A0478', '192U1A0479', '192U1A0480', '192U1A0481', '192U1A0482', '192U1A0483', '192U1A0484', '192U1A0485', '192U1A0486', '192U1A0487', '192U1A0488', '192U1A0489', '192U1A0490', '192U1A0491', '192U1A0492', '192U1A0493', '192U1A0494', '192U1A0495', '192U1A0496', '192U1A0497', '192U1A0498', '192U1A0499']
99
[40  5 79 31  3 71 89 91  1 66 49  0  0 55 19 65 87 68 55 26 65 78  8 84
 48 82 36 41 26 30 84 26 69 54 22 99 52 50 47 27 57 62 62 93 47 10 54 14
 78 30 27 88 82 53 60 68 75 77 27 61  0 59 38  0 23 43  3 37 71 64  3 65
 47 76  3  7 80 60 74 41 65 41 60 17 75 14 94 12 13 96 16 80  0 17 18 95
  8 61 74]
99

In [4]:
student={
    "RollNumbers":Roll_numbers,
    "EMTL":EMTL,
    "CO":CO,
    "AWP":AWP
}

In [5]:
student

{'RollNumbers': ['192U1A0401',
  '192U1A0402',
  '192U1A0403',
  '192U1A0404',
  '192U1A0405',
  '192U1A0406',
  '192U1A0407',
  '192U1A0408',
  '192U1A0409',
  '192U1A0410',
  '192U1A0411',
  '192U1A0412',
  '192U1A0413',
  '192U1A0414',
  '192U1A0415',
  '192U1A0416',
  '192U1A0417',
  '192U1A0418',
  '192U1A0419',
  '192U1A0420',
  '192U1A0421',
  '192U1A0422',
  '192U1A0423',
  '192U1A0424',
  '192U1A0425',
  '192U1A0426',
  '192U1A0427',
  '192U1A0428',
  '192U1A0429',
  '192U1A0430',
  '192U1A0431',
  '192U1A0432',
  '192U1A0433',
  '192U1A0434',
  '192U1A0435',
  '192U1A0436',
  '192U1A0437',
  '192U1A0438',
  '192U1A0439',
  '192U1A0440',
  '192U1A0441',
  '192U1A0442',
  '192U1A0443',
  '192U1A0444',
  '192U1A0445',
  '192U1A0446',
  '192U1A0447',
  '192U1A0448',
  '192U1A0449',
  '192U1A0450',
  '192U1A0451',
  '192U1A0452',
  '192U1A0453',
  '192U1A0454',
  '192U1A0455',
  '192U1A0456',
  '192U1A0457',
  '192U1A0458',
  '192U1A0459',
  '192U1A0460',
  '192U1A0461',
  '192U1A0462',
  '192U1A0463',
  '192U1A0464',
  '192U1A0465',
  '192U1A0466',
  '192U1A0467',
  '192U1A0468',
  '192U1A0469',
  '192U1A0470',
  '192U1A0471',
  '192U1A0472',
  '192U1A0473',
  '192U1A0474',
  '192U1A0475',
  '192U1A0476',
  '192U1A0477',
  '192U1A0478',
  '192U1A0479',
  '192U1A0480',
  '192U1A0481',
  '192U1A0482',
  '192U1A0483',
  '192U1A0484',
  '192U1A0485',
  '192U1A0486',
  '192U1A0487',
  '192U1A0488',
  '192U1A0489',
  '192U1A0490',
  '192U1A0491',
  '192U1A0492',
  '192U1A0493',
  '192U1A0494',
  '192U1A0495',
  '192U1A0496',
  '192U1A0497',
  '192U1A0498',
  '192U1A0499'],
 'EMTL': array([82, 26, 94, 22, 30, 70,  5, 24, 58, 81, 96, 31, 50, 66, 68, 57, 59,
        66, 52,  0, 15, 18, 65, 97, 94, 72, 64, 73, 76, 85, 76, 84, 50, 25,
        41, 18, 93, 72,  1, 40,  3, 85, 47, 73,  9, 40, 67, 26, 20, 94, 13,
        77, 78, 23,  8, 33, 97, 82, 38, 58,  2, 92, 79, 66, 39, 26, 58, 17,
        68, 35, 93, 23, 60, 79, 73,  7, 10, 41, 17, 30,  4, 70, 82, 92, 77,
        33,  5, 38, 54, 48, 16, 98, 41, 74, 85, 89, 62, 27, 29]),
 'CO': array([67, 54, 15, 34, 23,  6, 27, 52, 90, 69, 52,  8,  8,  8, 80, 10, 99,
        71, 97, 17, 74, 55, 67, 18, 55, 52, 13, 33, 72, 40,  6, 26, 17, 99,
        65, 24, 32, 25, 84, 16, 99, 29, 41, 31, 73, 75, 63, 60, 85, 12, 10,
        77,  0, 74, 20, 66, 18, 95, 89, 98, 52, 74, 47, 31, 49, 71, 21, 34,
        91, 34, 70, 84, 54, 30, 62, 43,  6, 47, 37, 78, 25, 21, 46, 33, 12,
        11, 68, 87, 23, 60, 34, 50, 89, 44, 56,  0, 59, 82, 20]),
 'AWP': array([55,  1, 53, 55, 25, 74, 73, 49,  5, 31, 48, 18, 67, 13, 92, 36, 79,
        39, 81, 43, 53, 24, 10, 61, 58, 41, 64, 93, 69, 70, 35, 17, 77, 97,
        12,  8, 91, 55, 46, 14, 58, 72, 72, 82, 23, 24, 33, 13,  6,  6, 82,
        67, 21, 63, 12, 46, 45, 26, 22, 52, 97, 41, 64, 24, 83, 30, 89, 76,
        82, 31,  8,  6, 69,  0, 49, 17, 70, 74, 92,  9, 37, 24, 12, 31, 72,
        63, 97, 49, 14, 17, 17, 82, 32, 46, 45, 35, 98, 29, 30])}

In [6]:
F_STD=pd.DataFrame(student)
F_STD

   RollNumbers  EMTL  CO  AWP
0   192U1A0401    82  67   55
1   192U1A0402    26  54    1
2   192U1A0403    94  15   53
3   192U1A0404    22  34   55
4   192U1A0405    30  23   25
5   192U1A0406    70   6   74
6   192U1A0407     5  27   73
7   192U1A0408    24  52   49
8   192U1A0409    58  90    5
9   192U1A0410    81  69   31
10  192U1A0411    96  52   48
11  192U1A0412    31   8   18
12  192U1A0413    50   8   67
13  192U1A0414    66   8   13
14  192U1A0415    68  80   92
15  192U1A0416    57  10   36
16  192U1A0417    59  99   79
17  192U1A0418    66  71   39
18  192U1A0419    52  97   81
19  192U1A0420     0  17   43
20  192U1A0421    15  74   53
21  192U1A0422    18  55   24
22  192U1A0423    65  67   10
23  192U1A0424    97  18   61
24  192U1A0425    94  55   58
25  192U1A0426    72  52   41
26  192U1A0427    64  13   64
27  192U1A0428    73  33   93
28  192U1A0429    76  72   69
29  192U1A0430    85  40   70
..         ...   ...  ..  ...
69  192U1A0470    35  34   31
70  192U1A0471    93  70    8
71  192U1A0472    23  84    6
72  192U1A0473    60  54   69
73  192U1A0474    79  30    0
74  192U1A0475    73  62   49
75  192U1A0476     7  43   17
76  192U1A0477    10   6   70
77  192U1A0478    41  47   74
78  192U1A0479    17  37   92
79  192U1A0480    30  78    9
80  192U1A0481     4  25   37
81  192U1A0482    70  21   24
82  192U1A0483    82  46   12
83  192U1A0484    92  33   31
84  192U1A0485    77  12   72
85  192U1A0486    33  11   63
86  192U1A0487     5  68   97
87  192U1A0488    38  87   49
88  192U1A0489    54  23   14
89  192U1A0490    48  60   17
90  192U1A0491    16  34   17
91  192U1A0492    98  50   82
92  192U1A0493    41  89   32
93  192U1A0494    74  44   46
94  192U1A0495    85  56   45
95  192U1A0496    89   0   35
96  192U1A0497    62  59   98
97  192U1A0498    27  82   29
98  192U1A0499    29  20   30

[99 rows x 4 columns]

In [7]:
F_STD.head()

  RollNumbers  EMTL  CO  AWP
0  192U1A0401    82  67   55
1  192U1A0402    26  54    1
2  192U1A0403    94  15   53
3  192U1A0404    22  34   55
4  192U1A0405    30  23   25

In [8]:
F_STD.head(10)

  RollNumbers  EMTL  CO  AWP
0  192U1A0401    82  67   55
1  192U1A0402    26  54    1
2  192U1A0403    94  15   53
3  192U1A0404    22  34   55
4  192U1A0405    30  23   25
5  192U1A0406    70   6   74
6  192U1A0407     5  27   73
7  192U1A0408    24  52   49
8  192U1A0409    58  90    5
9  192U1A0410    81  69   31

In [9]:
F_STD.tail()

   RollNumbers  EMTL  CO  AWP
94  192U1A0495    85  56   45
95  192U1A0496    89   0   35
96  192U1A0497    62  59   98
97  192U1A0498    27  82   29
98  192U1A0499    29  20   30

In [10]:
F_STD.tail(10)

   RollNumbers  EMTL  CO  AWP
89  192U1A0490    48  60   17
90  192U1A0491    16  34   17
91  192U1A0492    98  50   82
92  192U1A0493    41  89   32
93  192U1A0494    74  44   46
94  192U1A0495    85  56   45
95  192U1A0496    89   0   35
96  192U1A0497    62  59   98
97  192U1A0498    27  82   29
98  192U1A0499    29  20   30

In [11]:
F_STD['EMTL']

0     82
1     26
2     94
3     22
4     30
5     70
6      5
7     24
8     58
9     81
10    96
11    31
12    50
13    66
14    68
15    57
16    59
17    66
18    52
19     0
20    15
21    18
22    65
23    97
24    94
25    72
26    64
27    73
28    76
29    85
      ..
69    35
70    93
71    23
72    60
73    79
74    73
75     7
76    10
77    41
78    17
79    30
80     4
81    70
82    82
83    92
84    77
85    33
86     5
87    38
88    54
89    48
90    16
91    98
92    41
93    74
94    85
95    89
96    62
97    27
98    29
Name: EMTL, Length: 99, dtype: int32

In [12]:
F_STD[['EMTL','CO']]

    EMTL  CO
0     82  67
1     26  54
2     94  15
3     22  34
4     30  23
5     70   6
6      5  27
7     24  52
8     58  90
9     81  69
10    96  52
11    31   8
12    50   8
13    66   8
14    68  80
15    57  10
16    59  99
17    66  71
18    52  97
19     0  17
20    15  74
21    18  55
22    65  67
23    97  18
24    94  55
25    72  52
26    64  13
27    73  33
28    76  72
29    85  40
..   ...  ..
69    35  34
70    93  70
71    23  84
72    60  54
73    79  30
74    73  62
75     7  43
76    10   6
77    41  47
78    17  37
79    30  78
80     4  25
81    70  21
82    82  46
83    92  33
84    77  12
85    33  11
86     5  68
87    38  87
88    54  23
89    48  60
90    16  34
91    98  50
92    41  89
93    74  44
94    85  56
95    89   0
96    62  59
97    27  82
98    29  20

[99 rows x 2 columns]

In [14]:
F_STD.iloc[50:60]

   RollNumbers  EMTL  CO  AWP
50  192U1A0451    13  10   82
51  192U1A0452    77  77   67
52  192U1A0453    78   0   21
53  192U1A0454    23  74   63
54  192U1A0455     8  20   12
55  192U1A0456    33  66   46
56  192U1A0457    97  18   45
57  192U1A0458    82  95   26
58  192U1A0459    38  89   22
59  192U1A0460    58  98   52

In [15]:
F_STD.iloc[50:60][['EMTL',"AWP"]]

    EMTL  AWP
50    13   82
51    77   67
52    78   21
53    23   63
54     8   12
55    33   46
56    97   45
57    82   26
58    38   22
59    58   52

In [16]:
F_STD.iloc[35]

RollNumbers    192U1A0436
EMTL                   18
CO                     24
AWP                     8
Name: 35, dtype: object

In [19]:
F_STD.iloc[35][['RollNumbers','AWP']]

RollNumbers    192U1A0436
AWP                     8
Name: 35, dtype: object

In [21]:
F2=F_STD.set_index('RollNumbers')
F2

             EMTL  CO  AWP
RollNumbers
192U1A0401     82  67   55
192U1A0402     26  54    1
192U1A0403     94  15   53
192U1A0404     22  34   55
192U1A0405     30  23   25
192U1A0406     70   6   74
192U1A0407      5  27   73
192U1A0408     24  52   49
192U1A0409     58  90    5
192U1A0410     81  69   31
192U1A0411     96  52   48
192U1A0412     31   8   18
192U1A0413     50   8   67
192U1A0414     66   8   13
192U1A0415     68  80   92
192U1A0416     57  10   36
192U1A0417     59  99   79
192U1A0418     66  71   39
192U1A0419     52  97   81
192U1A0420      0  17   43
192U1A0421     15  74   53
192U1A0422     18  55   24
192U1A0423     65  67   10
192U1A0424     97  18   61
192U1A0425     94  55   58
192U1A0426     72  52   41
192U1A0427     64  13   64
192U1A0428     73  33   93
192U1A0429     76  72   69
192U1A0430     85  40   70
...           ...  ..  ...
192U1A0470     35  34   31
192U1A0471     93  70    8
192U1A0472     23  84    6
192U1A0473     60  54   69
192U1A0474     79  30    0
192U1A0475     73  62   49
192U1A0476      7  43   17
192U1A0477     10   6   70
192U1A0478     41  47   74
192U1A0479     17  37   92
192U1A0480     30  78    9
192U1A0481      4  25   37
192U1A0482     70  21   24
192U1A0483     82  46   12
192U1A0484     92  33   31
192U1A0485     77  12   72
192U1A0486     33  11   63
192U1A0487      5  68   97
192U1A0488     38  87   49
192U1A0489     54  23   14
192U1A0490     48  60   17
192U1A0491     16  34   17
192U1A0492     98  50   82
192U1A0493     41  89   32
192U1A0494     74  44   46
192U1A0495     85  56   45
192U1A0496     89   0   35
192U1A0497     62  59   98
192U1A0498     27  82   29
192U1A0499     29  20   30

[99 rows x 3 columns]

In [23]:
F2.sum(axis='columns')

RollNumbers
192U1A0401    204
192U1A0402     81
192U1A0403    162
192U1A0404    111
192U1A0405     78
192U1A0406    150
192U1A0407    105
192U1A0408    125
192U1A0409    153
192U1A0410    181
192U1A0411    196
192U1A0412     57
192U1A0413    125
192U1A0414     87
192U1A0415    240
192U1A0416    103
192U1A0417    237
192U1A0418    176
192U1A0419    230
192U1A0420     60
192U1A0421    142
192U1A0422     97
192U1A0423    142
192U1A0424    176
192U1A0425    207
192U1A0426    165
192U1A0427    141
192U1A0428    199
192U1A0429    217
192U1A0430    195
             ...
192U1A0470    100
192U1A0471    171
192U1A0472    113
192U1A0473    183
192U1A0474    109
192U1A0475    184
192U1A0476     67
192U1A0477     86
192U1A0478    162
192U1A0479    146
192U1A0480    117
192U1A0481     66
192U1A0482    115
192U1A0483    140
192U1A0484    156
192U1A0485    161
192U1A0486    107
192U1A0487    170
192U1A0488    174
192U1A0489     91
192U1A0490    125
192U1A0491     67
192U1A0492    230
192U1A0493    162
192U1A0494    164
192U1A0495    186
192U1A0496    124
192U1A0497    219
192U1A0498    138
192U1A0499     79
Length: 99, dtype: int64

In [24]:
F2['TOTAL']=F2.sum(axis='columns')
F2

             EMTL  CO  AWP  TOTAL
RollNumbers
192U1A0401     82  67   55    204
192U1A0402     26  54    1     81
192U1A0403     94  15   53    162
192U1A0404     22  34   55    111
192U1A0405     30  23   25     78
192U1A0406     70   6   74    150
192U1A0407      5  27   73    105
192U1A0408     24  52   49    125
192U1A0409     58  90    5    153
192U1A0410     81  69   31    181
192U1A0411     96  52   48    196
192U1A0412     31   8   18     57
192U1A0413     50   8   67    125
192U1A0414     66   8   13     87
192U1A0415     68  80   92    240
192U1A0416     57  10   36    103
192U1A0417     59  99   79    237
192U1A0418     66  71   39    176
192U1A0419     52  97   81    230
192U1A0420      0  17   43     60
192U1A0421     15  74   53    142
192U1A0422     18  55   24     97
192U1A0423     65  67   10    142
192U1A0424     97  18   61    176
192U1A0425     94  55   58    207
192U1A0426     72  52   41    165
192U1A0427     64  13   64    141
192U1A0428     73  33   93    199
192U1A0429     76  72   69    217
192U1A0430     85  40   70    195
...           ...  ..  ...    ...
192U1A0470     35  34   31    100
192U1A0471     93  70    8    171
192U1A0472     23  84    6    113
192U1A0473     60  54   69    183
192U1A0474     79  30    0    109
192U1A0475     73  62   49    184
192U1A0476      7  43   17     67
192U1A0477     10   6   70     86
192U1A0478     41  47   74    162
192U1A0479     17  37   92    146
192U1A0480     30  78    9    117
192U1A0481      4  25   37     66
192U1A0482     70  21   24    115
192U1A0483     82  46   12    140
192U1A0484     92  33   31    156
192U1A0485     77  12   72    161
192U1A0486     33  11   63    107
192U1A0487      5  68   97    170
192U1A0488     38  87   49    174
192U1A0489     54  23   14     91
192U1A0490     48  60   17    125
192U1A0491     16  34   17     67
192U1A0492     98  50   82    230
192U1A0493     41  89   32    162
192U1A0494     74  44   46    164
192U1A0495     85  56   45    186
192U1A0496     89   0   35    124
192U1A0497     62  59   98    219
192U1A0498     27  82   29    138
192U1A0499     29  20   30     79

[99 rows x 4 columns]

In [25]:
F2.head()

             EMTL  CO  AWP  TOTAL
RollNumbers
192U1A0401     82  67   55    204
192U1A0402     26  54    1     81
192U1A0403     94  15   53    162
192U1A0404     22  34   55    111
192U1A0405     30  23   25     78

In [27]:
(F2['TOTAL']*100)/300

RollNumbers
192U1A0401    68.000000
192U1A0402    27.000000
192U1A0403    54.000000
192U1A0404    37.000000
192U1A0405    26.000000
192U1A0406    50.000000
192U1A0407    35.000000
192U1A0408    41.666667
192U1A0409    51.000000
192U1A0410    60.333333
192U1A0411    65.333333
192U1A0412    19.000000
192U1A0413    41.666667
192U1A0414    29.000000
192U1A0415    80.000000
192U1A0416    34.333333
192U1A0417    79.000000
192U1A0418    58.666667
192U1A0419    76.666667
192U1A0420    20.000000
192U1A0421    47.333333
192U1A0422    32.333333
192U1A0423    47.333333
192U1A0424    58.666667
192U1A0425    69.000000
192U1A0426    55.000000
192U1A0427    47.000000
192U1A0428    66.333333
192U1A0429    72.333333
192U1A0430    65.000000
                ...
192U1A0470    33.333333
192U1A0471    57.000000
192U1A0472    37.666667
192U1A0473    61.000000
192U1A0474    36.333333
192U1A0475    61.333333
192U1A0476    22.333333
192U1A0477    28.666667
192U1A0478    54.000000
192U1A0479    48.666667
192U1A0480    39.000000
192U1A0481    22.000000
192U1A0482    38.333333
192U1A0483    46.666667
192U1A0484    52.000000
192U1A0485    53.666667
192U1A0486    35.666667
192U1A0487    56.666667
192U1A0488    58.000000
192U1A0489    30.333333
192U1A0490    41.666667
192U1A0491    22.333333
192U1A0492    76.666667
192U1A0493    54.000000
192U1A0494    54.666667
192U1A0495    62.000000
192U1A0496    41.333333
192U1A0497    73.000000
192U1A0498    46.000000
192U1A0499    26.333333
Name: TOTAL, Length: 99, dtype: float64

In [28]:
F2['PERCENTAGE']=(F2['TOTAL']*100)/300

In [29]:
F2

             EMTL  CO  AWP  TOTAL  PERCENTAGE
RollNumbers
192U1A0401     82  67   55    204   68.000000
192U1A0402     26  54    1     81   27.000000
192U1A0403     94  15   53    162   54.000000
192U1A0404     22  34   55    111   37.000000
192U1A0405     30  23   25     78   26.000000
192U1A0406     70   6   74    150   50.000000
192U1A0407      5  27   73    105   35.000000
192U1A0408     24  52   49    125   41.666667
192U1A0409     58  90    5    153   51.000000
192U1A0410     81  69   31    181   60.333333
192U1A0411     96  52   48    196   65.333333
192U1A0412     31   8   18     57   19.000000
192U1A0413     50   8   67    125   41.666667
192U1A0414     66   8   13     87   29.000000
192U1A0415     68  80   92    240   80.000000
192U1A0416     57  10   36    103   34.333333
192U1A0417     59  99   79    237   79.000000
192U1A0418     66  71   39    176   58.666667
192U1A0419     52  97   81    230   76.666667
192U1A0420      0  17   43     60   20.000000
192U1A0421     15  74   53    142   47.333333
192U1A0422     18  55   24     97   32.333333
192U1A0423     65  67   10    142   47.333333
192U1A0424     97  18   61    176   58.666667
192U1A0425     94  55   58    207   69.000000
192U1A0426     72  52   41    165   55.000000
192U1A0427     64  13   64    141   47.000000
192U1A0428     73  33   93    199   66.333333
192U1A0429     76  72   69    217   72.333333
192U1A0430     85  40   70    195   65.000000
...           ...  ..  ...    ...         ...
192U1A0470     35  34   31    100   33.333333
192U1A0471     93  70    8    171   57.000000
192U1A0472     23  84    6    113   37.666667
192U1A0473     60  54   69    183   61.000000
192U1A0474     79  30    0    109   36.333333
192U1A0475     73  62   49    184   61.333333
192U1A0476      7  43   17     67   22.333333
192U1A0477     10   6   70     86   28.666667
192U1A0478     41  47   74    162   54.000000
192U1A0479     17  37   92    146   48.666667
192U1A0480     30  78    9    117   39.000000
192U1A0481      4  25   37     66   22.000000
192U1A0482     70  21   24    115   38.333333
192U1A0483     82  46   12    140   46.666667
192U1A0484     92  33   31    156   52.000000
192U1A0485     77  12   72    161   53.666667
192U1A0486     33  11   63    107   35.666667
192U1A0487      5  68   97    170   56.666667
192U1A0488     38  87   49    174   58.000000
192U1A0489     54  23   14     91   30.333333
192U1A0490     48  60   17    125   41.666667
192U1A0491     16  34   17     67   22.333333
192U1A0492     98  50   82    230   76.666667
192U1A0493     41  89   32    162   54.000000
192U1A0494     74  44   46    164   54.666667
192U1A0495     85  56   45    186   62.000000
192U1A0496     89   0   35    124   41.333333
192U1A0497     62  59   98    219   73.000000
192U1A0498     27  82   29    138   46.000000
192U1A0499     29  20   30     79   26.333333

[99 rows x 5 columns]

In [31]:
F2['GRADE']=np.zeros(99,dtype='str')

In [34]:
F2['GRADE'][F2['PERCENTAGE']>=35]="P"

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [36]:
F2['GRADE'][F2['PERCENTAGE']<35]="F"

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [37]:
F2

             EMTL  CO  AWP  TOTAL  PERCENTAGE GRADE
RollNumbers
192U1A0401     82  67   55    204   68.000000     P
192U1A0402     26  54    1     81   27.000000     F
192U1A0403     94  15   53    162   54.000000     P
192U1A0404     22  34   55    111   37.000000     P
192U1A0405     30  23   25     78   26.000000     F
192U1A0406     70   6   74    150   50.000000     P
192U1A0407      5  27   73    105   35.000000     P
192U1A0408     24  52   49    125   41.666667     P
192U1A0409     58  90    5    153   51.000000     P
192U1A0410     81  69   31    181   60.333333     P
192U1A0411     96  52   48    196   65.333333     P
192U1A0412     31   8   18     57   19.000000     F
192U1A0413     50   8   67    125   41.666667     P
192U1A0414     66   8   13     87   29.000000     F
192U1A0415     68  80   92    240   80.000000     P
192U1A0416     57  10   36    103   34.333333     F
192U1A0417     59  99   79    237   79.000000     P
192U1A0418     66  71   39    176   58.666667     P
192U1A0419     52  97   81    230   76.666667     P
192U1A0420      0  17   43     60   20.000000     F
192U1A0421     15  74   53    142   47.333333     P
192U1A0422     18  55   24     97   32.333333     F
192U1A0423     65  67   10    142   47.333333     P
192U1A0424     97  18   61    176   58.666667     P
192U1A0425     94  55   58    207   69.000000     P
192U1A0426     72  52   41    165   55.000000     P
192U1A0427     64  13   64    141   47.000000     P
192U1A0428     73  33   93    199   66.333333     P
192U1A0429     76  72   69    217   72.333333     P
192U1A0430     85  40   70    195   65.000000     P
...           ...  ..  ...    ...         ...   ...
192U1A0470     35  34   31    100   33.333333     F
192U1A0471     93  70    8    171   57.000000     P
192U1A0472     23  84    6    113   37.666667     P
192U1A0473     60  54   69    183   61.000000     P
192U1A0474     79  30    0    109   36.333333     P
192U1A0475     73  62   49    184   61.333333     P
192U1A0476      7  43   17     67   22.333333     F
192U1A0477     10   6   70     86   28.666667     F
192U1A0478     41  47   74    162   54.000000     P
192U1A0479     17  37   92    146   48.666667     P
192U1A0480     30  78    9    117   39.000000     P
192U1A0481      4  25   37     66   22.000000     F
192U1A0482     70  21   24    115   38.333333     P
192U1A0483     82  46   12    140   46.666667     P
192U1A0484     92  33   31    156   52.000000     P
192U1A0485     77  12   72    161   53.666667     P
192U1A0486     33  11   63    107   35.666667     P
192U1A0487      5  68   97    170   56.666667     P
192U1A0488     38  87   49    174   58.000000     P
192U1A0489     54  23   14     91   30.333333     F
192U1A0490     48  60   17    125   41.666667     P
192U1A0491     16  34   17     67   22.333333     F
192U1A0492     98  50   82    230   76.666667     P
192U1A0493     41  89   32    162   54.000000     P
192U1A0494     74  44   46    164   54.666667     P
192U1A0495     85  56   45    186   62.000000     P
192U1A0496     89   0   35    124   41.333333     P
192U1A0497     62  59   98    219   73.000000     P
192U1A0498     27  82   29    138   46.000000     P
192U1A0499     29  20   30     79   26.333333     F

[99 rows x 6 columns]